// Article type definition
export interface Article {
  id: string;
  title: string;
  subtitle?: string;
  titleEn: string;
  slug: string;
  description: string;
  category: "ux-research" | "ux-design" | "kariyer" | "araclar-ipucu" | "temel-kavramlar";
  readingTime: number;
  featured: boolean;
  publishedAt: string;
  heroImage?: string;
  author?: string;
  views?: number;
}

// Mock articles data - Updated with all 23 articles
export const MOCK_ARTICLES: Article[] = [
  {
    id: "kullanilabilirlik-testi",
    title: "Kullanılabilirlik Testi Nedir?",
    subtitle: "Adım Adım Uygulama Rehberi",
    titleEn: "Usability Testing",
    slug: "kullanilabilirlik-testi",
    description: "Tasarımlarını gerçek kullanıcılarla test etmenin en etkili yolu. Kullanılabilirlik testinin ne olduğunu, neden önemli olduğunu ve adım adım nasıl uygulayacağını öğren.",
    category: "ux-research",
    readingTime: 12,
    featured: true,
    publishedAt: "2025-01-13",
    heroImage: "https://r.resimlink.com/76fDGw31VzEL.png",
    author: "DesignAtlas",
    views: 1250,
  },
  {
    id: "portfolio-case-study",
    title: "Portfolio Case Study Nasıl Yazılır?",
    subtitle: "İş Bulmanı Sağlayacak Case Study Rehberi",
    titleEn: "Portfolio Case Study",
    slug: "portfolio-case-study",
    description: "UX portfolio case study nasıl yazılır? Hiring manager'ların dikkatini çeken, süreç odaklı ve ikna edici case study oluşturma rehberi.",
    category: "kariyer",
    readingTime: 15,
    featured: true,
    publishedAt: "2025-01-13",
    heroImage: "https://r.resimlink.com/MiVUPTfO.png",
    author: "DesignAtlas",
    views: 2100,
  },
  {
    id: "user-flow-task-flow",
    title: "User Flow ve Task Flow: Fark ve Kullanım",
    subtitle: "İki Kavramı Doğru Anla, Doğru Kullan",
    titleEn: "User Flow vs Task Flow",
    slug: "user-flow-task-flow",
    description: "User flow ve task flow nedir, aralarındaki fark ne? Hangisini ne zaman kullanmalısın? Pratik örnekler ve şablonlarla akış diyagramı rehberi.",
    category: "ux-design",
    readingTime: 10,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "DesignAtlas",
    views: 1650,
  },
  {
    id: "kullanici-gorusmesi",
    title: "Kullanıcı Görüşmesi Nasıl Yapılır?",
    subtitle: "Etkili User Interview Rehberi",
    titleEn: "User Interview",
    slug: "kullanici-gorusmesi",
    description: "Kullanıcı görüşmesi nedir, nasıl yapılır? Doğru soru sorma teknikleri, görüşme planı oluşturma ve kullanıcıdan içgörü çıkarma rehberi.",
    category: "ux-research",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-13",
    heroImage: "",
    author: "DesignAtlas",
    views: 980,
  },
  {
    id: "ux-nedir",
    title: "UX Nedir?",
    subtitle: "Kullanıcı Deneyimi Tasarımına Giriş",
    titleEn: "What is UX?",
    slug: "ux-nedir",
    description: "UX (User Experience) nedir? Kullanıcı deneyimi tasarımı ne anlama gelir, neden önemlidir ve UX Designer ne yapar? Başlangıç seviyesi rehberi.",
    category: "temel-kavramlar",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "ui-nedir",
    title: "UI Nedir?",
    subtitle: "Kullanıcı Arayüzü Tasarımına Giriş",
    titleEn: "What is UI?",
    slug: "ui-nedir",
    description: "UI (User Interface) nedir? Kullanıcı arayüzü tasarımı ne anlama gelir, UI Designer ne yapar ve iyi bir arayüz nasıl olmalı? Başlangıç seviyesi rehberi.",
    category: "temel-kavramlar",
    readingTime: 11,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "ux-ui-farki",
    title: "UX ve UI Arasındaki Fark",
    subtitle: "İki Kavramı Bir Kez ve Herkes İçin Netleştirelim",
    titleEn: "UX vs UI",
    slug: "ux-ui-farki",
    description: "UX ve UI arasındaki fark nedir? UX Designer ile UI Designer ne yapar, nasıl çalışırlar? Karıştırılan bu iki kavramı örneklerle açıklıyoruz.",
    category: "temel-kavramlar",
    readingTime: 9,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "wireframe-nedir",
    title: "Wireframe Nedir?",
    subtitle: "Tasarımın İskeletini Oluşturma Rehberi",
    titleEn: "What is Wireframe?",
    slug: "wireframe-nedir",
    description: "Wireframe nedir, ne işe yarar? Wireframe nasıl çizilir, hangi araçlar kullanılır? Low-fidelity tasarımın temellerini öğren.",
    category: "ux-design",
    readingTime: 11,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "persona-olusturma",
    title: "Persona Oluşturma Rehberi",
    subtitle: "Kullanıcılarını Somutlaştırmanın Yolu",
    titleEn: "Creating Personas",
    slug: "persona-olusturma",
    description: "Persona nedir, nasıl oluşturulur? Kullanıcı araştırmasından persona çıkarma, persona şablonu ve kullanım rehberi. Örneklerle adım adım anlatım.",
    category: "ux-research",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "ux-mulakat-sorulari",
    title: "UX Mülakat Soruları ve Cevapları",
    subtitle: "İş Görüşmesine Hazırlık Rehberi",
    titleEn: "UX Interview Questions",
    slug: "ux-mulakat-sorulari",
    description: "UX Designer iş görüşmesinde en çok sorulan sorular ve nasıl cevaplanır? Davranışsal, teknik ve case study soruları için hazırlık rehberi.",
    category: "kariyer",
    readingTime: 16,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "product-design-nedir",
    title: "Product Design Nedir?",
    subtitle: "Ürün Tasarımcısının Rolü ve Sorumlulukları",
    titleEn: "What is Product Design?",
    slug: "product-design-nedir",
    description: "Product Design nedir? Product Designer ne yapar, UX Designer'dan farkı ne? Ürün tasarımcısının rolü, sorumlulukları ve kariyer yolu rehberi.",
    category: "temel-kavramlar",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "prototype-nedir",
    title: "Prototype Nedir?",
    subtitle: "Etkileşimli Tasarım Taslakları Oluşturma Rehberi",
    titleEn: "What is Prototype?",
    slug: "prototype-nedir",
    description: "Prototype nedir, ne işe yarar? Prototip nasıl oluşturulur, hangi araçlar kullanılır? Low-fi'dan high-fi'ya prototipleme rehberi.",
    category: "ux-design",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "wireframe-mockup-prototype",
    title: "Wireframe vs Mockup vs Prototype",
    subtitle: "Üç Tasarım Çıktısını Doğru Anla, Doğru Kullan",
    titleEn: "Wireframe vs Mockup vs Prototype",
    slug: "wireframe-mockup-prototype",
    description: "Wireframe, mockup ve prototype arasındaki farklar nedir? Hangisini ne zaman kullanmalısın? Karşılaştırmalı rehber ve pratik örnekler.",
    category: "ux-design",
    readingTime: 10,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "information-architecture",
    title: "Information Architecture Temelleri",
    subtitle: "İçeriği Organize Etmenin Sanatı",
    titleEn: "Information Architecture",
    slug: "information-architecture",
    description: "Information Architecture (IA) nedir? Bilgi mimarisi nasıl oluşturulur? Site haritası, navigasyon ve içerik organizasyonu rehberi.",
    category: "ux-design",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "user-journey-map",
    title: "User Journey Map Oluşturma",
    subtitle: "Kullanıcı Yolculuğunu Görselleştirme Rehberi",
    titleEn: "User Journey Mapping",
    slug: "user-journey-map",
    description: "User Journey Map nedir, nasıl oluşturulur? Kullanıcı yolculuğu haritası adım adım rehberi. Şablon, örnekler ve en iyi pratikler.",
    category: "ux-design",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "empathy-map",
    title: "Empathy Map Oluşturma",
    subtitle: "Kullanıcını Derinlemesine Anlamanın Yolu",
    titleEn: "Empathy Mapping",
    slug: "empathy-map",
    description: "Empathy Map nedir, nasıl oluşturulur? Kullanıcının düşüncelerini, duygularını ve davranışlarını anlamak için empati haritası rehberi.",
    category: "ux-research",
    readingTime: 11,
    featured: false,
    publishedAt: "2025-01-14",
    heroImage: "",
    author: "Serhat Bahçeliler",
    views: 0,
  },
  {
    id: "anket-tasarimi",
    title: "Anket Tasarımı: Doğru Soru Sorma",
    subtitle: "Etkili UX Anketi Oluşturma Rehberi",
    titleEn: "Survey Design",
    slug: "anket-tasarimi",
    description: "UX anketi nasıl tasarlanır? Doğru soru sorma teknikleri, soru tipleri, yaygın hatalar ve anket best practice'leri. Kapsamlı anket rehberi.",
    category: "ux-research",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "ab-test-temelleri",
    title: "A/B Test Temelleri",
    subtitle: "Veriyle Tasarım Kararı Alma Rehberi",
    titleEn: "A/B Testing Basics",
    slug: "ab-test-temelleri",
    description: "A/B test nedir, nasıl yapılır? Hipotez oluşturma, sample size, istatistiksel anlamlılık. Tasarımcılar için A/B test rehberi.",
    category: "ux-research",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "heuristic-evaluation",
    title: "Heuristic Evaluation Nedir?",
    subtitle: "Uzman Değerlendirmesiyle UX Sorunlarını Tespit Etme",
    titleEn: "Heuristic Evaluation",
    slug: "heuristic-evaluation",
    description: "Heuristic evaluation nedir, nasıl yapılır? Nielsen'in 10 sezgisel ilkesi, değerlendirme süreci ve şablon. Uzman UX denetimi rehberi.",
    category: "ux-research",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "design-system-nedir",
    title: "Design System Nedir?",
    subtitle: "Tutarlı Tasarımın Temeli",
    titleEn: "What is Design System?",
    slug: "design-system-nedir",
    description: "Design system nedir, neden önemli? Component library, style guide ve design token kavramları. Design system oluşturma ve kullanma rehberi.",
    category: "ux-design",
    readingTime: 15,
    featured: true,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "accessibility-temelleri",
    title: "Accessibility (Erişilebilirlik) Temelleri",
    subtitle: "Herkes İçin Tasarım",
    titleEn: "Accessibility Basics",
    slug: "accessibility-temelleri",
    description: "Erişilebilirlik nedir, neden önemli? WCAG standartları, erişilebilir tasarım ilkeleri ve pratik kontrol listesi. A11y rehberi.",
    category: "ux-design",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "micro-interactions",
    title: "Micro-interactions Tasarımı",
    subtitle: "Küçük Detaylar, Büyük Farklar",
    titleEn: "Micro-interactions Design",
    slug: "micro-interactions",
    description: "Micro-interaction nedir? Tetikleyiciler, kurallar, feedback ve döngüler. Kullanıcı deneyimini zenginleştiren küçük animasyonlar rehberi.",
    category: "ux-design",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "ux-writing-temelleri",
    title: "UX Writing Temelleri",
    subtitle: "Kullanıcıyla Doğru Kelimelerle Konuşma",
    titleEn: "UX Writing Basics",
    slug: "ux-writing-temelleri",
    description: "UX Writing nedir? Microcopy, hata mesajları, CTA yazımı ve ton of voice. Kullanıcı odaklı içerik yazma rehberi.",
    category: "ux-design",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "gestalt-ilkeleri",
    title: "Gestalt İlkeleri ve Görsel Algı",
    subtitle: "Tasarımın Psikolojik Temelleri",
    titleEn: "Gestalt Principles",
    slug: "gestalt-ilkeleri",
    description: "Gestalt ilkeleri nedir? Yakınlık, benzerlik, süreklilik, kapalılık ve diğer görsel algı prensipleri. UI tasarımda Gestalt kullanımı.",
    category: "temel-kavramlar",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-15",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "renk-teorisi",
    title: "Renk Teorisi ve UI'da Renk Kullanımı",
    subtitle: "Etkili Renk Paleti Oluşturma Rehberi",
    titleEn: "Color Theory for UI",
    slug: "renk-teorisi",
    description: "Renk teorisi nedir? Renk çarkı, renk harmonileri, UI'da renk kullanımı. Erişilebilir ve etkili renk paleti oluşturma rehberi.",
    category: "temel-kavramlar",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "tipografi-temelleri",
    title: "Tipografi Temelleri",
    subtitle: "UI'da Yazı Tipi Seçimi ve Kullanımı",
    titleEn: "Typography Basics",
    slug: "tipografi-temelleri",
    description: "Tipografi nedir? Font seçimi, type scale, line height, letter spacing. UI tasarımda okunabilir ve estetik tipografi rehberi.",
    category: "temel-kavramlar",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "gorsel-hiyerarsi",
    title: "Görsel Hiyerarşi Oluşturma",
    subtitle: "Kullanıcının Gözünü Yönlendirme Sanatı",
    titleEn: "Visual Hierarchy",
    slug: "gorsel-hiyerarsi",
    description: "Görsel hiyerarşi nedir? Boyut, renk, kontrast, boşluk ve konum ile dikkat yönetimi. UI'da etkili hiyerarşi oluşturma rehberi.",
    category: "ux-design",
    readingTime: 12,
    featured: false,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "spacing-layout-sistemleri",
    title: "Spacing ve Layout Sistemleri",
    subtitle: "Tutarlı Boşluk ve Düzen Oluşturma",
    titleEn: "Spacing and Layout Systems",
    slug: "spacing-layout-sistemleri",
    description: "Spacing sistemi nedir? 4px/8px grid, margin ve padding kuralları, layout grid kullanımı. Tutarlı ve ölçeklenebilir UI düzeni rehberi.",
    category: "ux-design",
    readingTime: 13,
    featured: false,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "responsive-design-temelleri",
    title: "Responsive Design Temelleri",
    subtitle: "Her Ekrana Uyumlu Tasarım",
    titleEn: "Responsive Design Basics",
    slug: "responsive-design-temelleri",
    description: "Responsive design nedir? Mobile-first yaklaşım, breakpoint'ler, fluid grid ve esnek görseller. Her ekran boyutuna uyumlu tasarım rehberi.",
    category: "ux-design",
    readingTime: 14,
    featured: false,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
  {
    id: "figma-temelleri",
    title: "Figma Temelleri",
    subtitle: "Sıfırdan Figma Öğrenme Rehberi",
    titleEn: "Figma Basics",
    slug: "figma-temelleri",
    description: "Figma nedir, nasıl kullanılır? Arayüz, temel araçlar, frame, component, auto layout. Başlangıç seviyesi Figma rehberi.",
    category: "araclar-ipucu",
    readingTime: 15,
    featured: true,
    publishedAt: "2025-01-16",
    heroImage: "",
    author: "DesignAtlas",
    views: 0,
  },
];
